const backendSkills = [
  {
    name: "Laravel",
    icon: "/images/code/laravel.svg",
    description: "PHP framework for building robust web applications and APIs.",
    mastery: 85,
    category: "Backend Framework",
    experience: "2+ years",
    projects: ["PasteIt.lol", "membercat.com", "Orvex"],
    actionText: "View Laravel Projects",
    actionLink: "#projects",
  },
  {
    name: "Node.js",
    icon: "/images/code/nodejs.svg",
    description: "JavaScript runtime for building fast, scalable servers.",
    mastery: 90,
    category: "Runtime Environment",
    experience: "2+ years",
    projects: ["DriftLabs", "NetherCore", "PteroLink"],
    actionText: "View Node.js Projects",
    actionLink: "#projects",
  },
  {
    name: "TypeScript",
    icon: "/images/code/typescript.svg",
    description: "Typed superset of JavaScript for large-scale applications.",
    mastery: 88,
    category: "Programming Language",
    experience: "2+ years",
    projects: ["DriftLabs", "NuboDB", "NetherCore"],
    actionText: "View TypeScript Projects",
    actionLink: "#projects",
  },
  {
    name: "GoLang",
    icon: "/images/code/golang.svg",
    description: "Statically typed, compiled language designed at Google.",
    mastery: 70,
    category: "Programming Language",
    experience: "1+ year",
    projects: ["DriftLabs", "Learning Projects"],
    actionText: "Learn More About Go",
    actionLink: "https://golang.org",
  },
  {
    name: "Python",
    icon: "/images/code/python.svg",
    description:
      "Powerful, readable language for everything from scripts to AI.",
    mastery: 75,
    category: "Programming Language",
    experience: "1+ year",
    projects: ["Scripts", "Automation Tools"],
    actionText: "View Python Projects",
    actionLink: "#projects",
  },
  {
    name: "Java",
    icon: "/images/code/gradle.svg",
    description: "Object-oriented language used for enterprise applications.",
    mastery: 65,
    category: "Programming Language",
    experience: "1+ year",
    projects: ["Performium Modpack", "Minecraft Plugins"],
    actionText: "View Java Projects",
    actionLink: "#projects",
  },
  {
    name: "MySQL",
    icon: "/images/code/mysql.svg",
    description: "Open-source relational database management system.",
    mastery: 80,
    category: "Database",
    experience: "2+ years",
    projects: ["Orvex", "PasteIt.lol", "membercat.com"],
    actionText: "View Database Projects",
    actionLink: "#projects",
  },
  {
    name: "Lua",
    icon: "/images/code/lua.svg",
    description: "Lightweight scripting language commonly used in games.",
    mastery: 60,
    category: "Scripting Language",
    experience: "6+ months",
    projects: ["Game Scripts", "Automation"],
    actionText: "Learn More About Lua",
    actionLink: "https://lua.org",
  },
];

const frontendSkills = [
  {
    name: "React",
    icon: "/images/code/react.svg",
    description: "Library for building modern UIs with reusable components.",
    mastery: 85,
    category: "Frontend Library",
    experience: "2+ years",
    projects: ["Portfolio", "PasteIt.lol", "membercat.com"],
    actionText: "View React Projects",
    actionLink: "#projects",
  },
  {
    name: "Svelte & SvelteKit",
    icon: "/images/code/svelte.svg",
    description:
      "Svelte is a modern frontend framework for building user interfaces.",
    mastery: 70,
    category: "Frontend Framework",
    experience: "1+ year",
    projects: ["Voxyn Labs"],
    actionText: "View Svelte Projects",
    actionLink: "#projects",
  },
  {
    name: "Next.js",
    icon: "/images/code/nextjs.svg",
    description: "React framework with SSR and static site generation.",
    mastery: 75,
    category: "Frontend Framework",
    experience: "1+ year",
    projects: ["Learning Projects"],
    actionText: "Learn More About Next.js",
    actionLink: "https://nextjs.org",
  },
  {
    name: "JavaScript",
    icon: "/images/code/javascript.svg",
    description: "High-level language for creating dynamic web content.",
    mastery: 90,
    category: "Programming Language",
    experience: "2+ years",
    projects: ["All Frontend Projects", "Discord Bots"],
    actionText: "View JavaScript Projects",
    actionLink: "#projects",
  },
  {
    name: "HTML",
    icon: "/images/code/html.svg",
    description: "Standard markup language for web page structure.",
    mastery: 95,
    category: "Markup Language",
    experience: "2+ years",
    projects: ["All Web Projects"],
    actionText: "View HTML Projects",
    actionLink: "#projects",
  },
  {
    name: "Tailwind CSS",
    icon: "/images/code/tailwindcss.svg",
    description: "Utility-first CSS framework for custom UI design.",
    mastery: 88,
    category: "CSS Framework",
    experience: "2+ years",
    projects: ["Portfolio", "PasteIt.lol", "Voxyn Labs"],
    actionText: "View Tailwind Projects",
    actionLink: "#projects",
  },
  {
    name: "Bootstrap",
    icon: "/images/code/bootstrap.svg",
    description: "Frontend framework for building responsive websites.",
    mastery: 75,
    category: "CSS Framework",
    experience: "1+ year",
    projects: ["Early Projects"],
    actionText: "Learn More About Bootstrap",
    actionLink: "https://getbootstrap.com",
  },
];

export { backendSkills, frontendSkills };
export default [...backendSkills, ...frontendSkills];
